services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-server-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
